This pr switches from rome to biome and adds github ci
openSUSE/cockpit-tukit pull request #38
Opened 2024-07-22 11:39 UTC by Lunarequest

Rome is no longer maintained. It was forked and turned into Biomejs. I've switched to biome and followed some lints and formatting. This also adds Github CI run on the registry.opensuse.org/opensuse/bci/nodejs:latest container. Everything seems to work just fine

2024-08-09 12:22 UTC, Lunarequest commented
@Nykseli can you review this, we have a successful build on obs using this pr

2024-08-09 12:30 UTC, Nykseli commented
The CI seems to be failing. After that's fixed, this can be merged

2024-08-12 09:22 UTC, Lunarequest commented
@Nykseli we have green CI!

2024-08-12 09:49 UTC, SludgeGirl commented
@Lunarequest Nice! It might be worth cleaning up the individual commits before merging though, just to keep the history nice and clean

2025-04-14 13:50 UTC, SludgeGirl commented
@Lunarequest how do you feel about picking this one back up? It would be good to move away from Rome

2025-04-14 13:58 UTC, Lunarequest commented
> @Lunarequest how do you feel about picking this one back up? It would be good to move away from Rome

yep, next on my list is picking this up again

2025-04-15 07:36 UTC, Lunarequest commented
> If the white space changes are needed please add a .git-blame-ignore-revs for commit [4d002ce](https://github.com/openSUSE/cockpit-tukit/commit/4d002ce086f7edc3bdb40eba547a7c902a7a1135) something along these lines: https://github.com/openSUSE/cockpit-subscriptions/blob/main/.git-blame-ignore-revs

done!

2025-04-15 07:38 UTC, SludgeGirl commented
A much more pedantic thing I've noticed, commits should follow a similar layout to:

```
Tools: Move SELinux policies to cockpit-selinux-policies

If SELinux isn't installed on the system when Cockpit is, the policies
are never installed. In order to handle this edge case, splitting out
the policies into their own package that we require if the system has or
requires in future the system policy

Co-Authored-By: Luna D Dragon <luna.dragon@suse.com>
```

You're often missing the space between the first line and the longer commit text like in 0a4572052aaccb3f7bbf68ef287e9f6da6599dd6

But like I said it's a more pedantic thing, the rest of these changes look good

2025-04-15 08:30 UTC, SludgeGirl requested changes

2025-04-15 08:30 UTC, SludgeGirl commented on .git-blame-ignore-revs
> +4d002ce086f7edc3bdb40eba547a7c902a7a1135
Actually can we add more of the comments to this? Something along the lines of the example I gave:

```
# If a commit modifies a ton of files and doesn't really contribute to the
# output of git-blame, please add it here
#
# 2025 - Initial fixing of eslint rules
4d002ce086f7edc3bdb40eba547a7c902a7a1135
```

2025-04-15 08:43 UTC, Lunarequest commented on .git-blame-ignore-revs
> +4d002ce086f7edc3bdb40eba547a7c902a7a1135
done

2025-04-15 08:54 UTC, SludgeGirl approved these changes

2025-04-15 08:54 UTC, merged